#!/usr/bin/python
""" File Tree Remover
    Removes Files in a File Tree from a given input.
"""


def main():
    """Validates Arguments, then runs File Tree Remover."""
    import sys
    from input_data import get_input_from_args
    from input_line_reader import process_many_lines
    from tree_worker import TreeWorker
    # Validate Arguments From System Input
    args = get_input_from_args(sys.argv)
    # Read the Input Tree File, Check the Input
    input_tree = args.get_tree_input()
    if input_tree is None or len(input_tree) < 1:
        raise ValueError("Tree Input not found, or empty.")
    # Process all Lines of text into procedural data
    procedural_data_sequence = process_many_lines(input_tree)
    if len(procedural_data_sequence) < 1:
        raise SystemExit("Empty Procedure")
    # Use this Worker to execute Stateful Procedural Operations
    worker = TreeWorker(args.data_dir)
    # Process one line at a time
    for data in procedural_data_sequence:
        if not worker.remove(data):
            raise Exception(
                "Invalid Operation: name=" + data.name + ", depth=" + data.depth
            )
    # Remove any Empty Directories remaining on the Stack
    worker.cleanup_path_stack()


if __name__ == "__main__":
    main()